### ISSUE TITLE
検索結果の数字を○で囲う

### ISSUE THREAD

**Issue by keisukee** [umezawann/Kanban-board#7]
![image](https://user-images.githubusercontent.com/38725877/135288135-3413d786-67d8-44dd-9749-d4d201e882b4.png)

イメージ↓
![image](https://user-images.githubusercontent.com/38725877/135288329-9115d2ba-39ee-4c80-a29b-00c84c83e8bb.png)

**Comment by umezawann** [comment]
![image](https://user-images.githubusercontent.com/79554925/135388428-f1dcf7b6-b92a-473c-9e96-621c7fec7baf.png)

task-5
